---
version: '3.8'
services:
  jenkins:
    restart: always
    image: ${DOCKER_REGISTRY}/jenkins:${VERSION}
    user: jenkins
    env_file:
      - ${dockerconfig_root}/jenkins/jenkins.config.env
    environment:
      JENKINS_HOME: ${JENKINS_HOME}
      HOME: ${JENKINS_HOME}
    expose:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    dns:
      - 172.17.0.1
      - 8.8.8.8
    volumes:
      #- ${dockerconfig_root}/ssh:${JENKINS_HOME}/.ssh
      # If you use the docker in the host these variables shall not be tinkered with
      - ${JENKINS_HOME}:${JENKINS_HOME}
  jenkins-data:
    image: busybox
    entrypoint: ["chown", "-R", "1000:1000", "${JENKINS_HOME}", "${JENKINS_HOME}/.ssh"]
    network_mode: "none"
    volumes:
      - ${JENKINS_HOME}:${JENKINS_HOME}
      #- ${dockerconfig_root}/ssh:${JENKINS_HOME}/.ssh
