---
version: '3.8'
services:
  jenkins:
    restart: unless-stopped
    image: ${DOCKER_REGISTRY}/jenkins:${VERSION}
    user: jenkins
    env_file:
      - ${dockerconfig_root}/jenkins/jenkins.config.env
    environment:
      JENKINS_HOME: ${JENKINS_HOME}
      HOME: ${JENKINS_HOME}
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      #- ${dockerconfig_root}/ssh:${JENKINS_HOME}/.ssh
      # If you use the docker in the host these variables shall not be tinkered with
      - ${JENKINS_HOME}:${JENKINS_HOME}
  jenkins-data:
    image: busybox
    entrypoint: ["chown", "-R", "1000:1000", "${JENKINS_HOME}", "${JENKINS_HOME}/.ssh"]
    network_mode: "none"
    volumes:
      - ${JENKINS_HOME}:${JENKINS_HOME}
      #- ${dockerconfig_root}/ssh:${JENKINS_HOME}/.ssh
